# Generated by Django 5.2.12 on 2026-03-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('software_used', models.CharField(max_length=200)),
                ('model_file_link', models.URLField(blank=True, help_text='Sketchfab ya Google Drive ka link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
