# Generated by Django 5.2.12 on 2026-03-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='video_snippet',
            field=models.FileField(blank=True, help_text='Hoover effect ke liye chota .mp4 video upload karein.', null=True, upload_to='videos/'),
        ),
    ]
