# Generated by Django 5.2.12 on 2026-03-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_model3d_video_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebGLProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(help_text='e.g. Interactive Experience', max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='webgl/')),
                ('live_link', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
