# Generated by Django 5.2.12 on 2026-04-07 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_portfoliovideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('software_used', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='projects/thumbnails/')),
                ('model_file_link', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='gallery.slidersection')),
            ],
        ),
    ]
