# Generated by Django 5.2.12 on 2026-04-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_project_options_alter_project_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='software_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
