# Generated by Django 5.2.12 on 2026-04-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_project_software_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='software_used',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
