# Generated by Django 5.2.12 on 2026-04-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_model3d_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedDoubleSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='featured_slider/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
