# Generated by Django 5.2.12 on 2026-04-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_featureddoubleslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigImageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='AR Experience', max_length=200)),
                ('image', models.ImageField(upload_to='big_images/')),
                ('ar_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
