# Generated by Django 5.2.12 on 2026-04-07 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_bigimagesection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featureddoubleslider',
            options={},
        ),
        migrations.RemoveField(
            model_name='featureddoubleslider',
            name='image',
        ),
        migrations.RemoveField(
            model_name='featureddoubleslider',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='featureddoubleslider',
            name='title',
        ),
        migrations.AddField(
            model_name='featureddoubleslider',
            name='name',
            field=models.CharField(default='Featured Slider', help_text='e.g. Featured Showcase 1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='featured_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_items', to='gallery.featureddoubleslider'),
        ),
    ]
