# Generated by Django 5.2.12 on 2026-04-07 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_alter_featureddoubleslider_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='video_snippet',
            field=models.FileField(blank=True, help_text='Hover effect ke liye chota .mp4 video upload karein.', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='gallery.slidersection'),
        ),
    ]
