# Generated by Django 5.2.12 on 2026-04-07 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_alter_model3d_video_snippet_alter_project_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebGLProject',
        ),
    ]
