# Generated by Django 5.2.12 on 2026-04-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_delete_webglproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='ar_products/')),
                ('ar_link', models.URLField(max_length=500)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
