# Generated by Django 5.2.12 on 2026-04-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_arproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='about_photos/')),
                ('experience_years', models.DecimalField(decimal_places=1, default=8.5, max_digits=4)),
            ],
        ),
    ]
