# Generated by Django 5.2.12 on 2026-08-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_aboutsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arproduct',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='featureddoubleslider',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='model3d',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='portfoliovideo',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='slidersection',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='photo_path',
            field=models.CharField(blank=True, help_text='Permanent photo path. Example: gallery/assets/images/sandeep-profile.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='arproduct',
            name='image_path',
            field=models.CharField(blank=True, help_text='Permanent image path. Example: gallery/assets/images/ar-product-01.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='bigimagesection',
            name='image_path',
            field=models.CharField(blank=True, help_text='Permanent image path. Example: gallery/assets/images/ar-view-main.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='model3d',
            name='image_path',
            field=models.CharField(blank=True, help_text='Permanent image path. Example: gallery/assets/images/product-design-01.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='model3d',
            name='video_path',
            field=models.CharField(blank=True, help_text='Permanent video path. Example: gallery/assets/videos/product-animation.mp4', max_length=500),
        ),
        migrations.AddField(
            model_name='portfoliovideo',
            name='video_path',
            field=models.CharField(blank=True, help_text='Permanent video path. Example: gallery/assets/videos/walk-through.mp4', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='image_path',
            field=models.CharField(blank=True, help_text='Permanent image path. Example: gallery/assets/images/airstream-front.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='about_photos/'),
        ),
        migrations.AlterField(
            model_name='arproduct',
            name='ar_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='arproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ar_products/'),
        ),
        migrations.AlterField(
            model_name='bigimagesection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='big_images/'),
        ),
        migrations.AlterField(
            model_name='featureddoubleslider',
            name='name',
            field=models.CharField(help_text='Example: Featured Showcase', max_length=200),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='model_file_link',
            field=models.URLField(blank=True, help_text='Sketchfab, Google Drive ya kisi external model ka link.'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='video_snippet',
            field=models.FileField(blank=True, help_text='Optional uploaded hover video.', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='portfoliovideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='projects/videos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0, help_text='0, 1, 2, 3... ke through display order set karein.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='projects/thumbnails/'),
        ),
    ]
